env:
 - RACKET_VERSION=7.0

before_install:
- git clone https://github.com/greghendershott/travis-racket.git
- cat travis-racket/install-racket.sh | bash # pipe to bash not sh!

script:
 - /usr/racket/bin/raco make main.rkt
 - /usr/racket/bin/raco test main.rkt
